version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "backend/"
    schedule:
      interval: "daily"
    assignees:
      - "sys27"
    groups:
      ef-core:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      aspnet:
        patterns:
          - "Microsoft.AspNetCore*"

  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
    assignees:
      - "sys27"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "sys27"
