version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "backend/"
    schedule:
      interval: "weekly"
    assignees:
      - "sys27"
    cooldown:
      default-days: 7
    groups:
      ef-core:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      aspnet:
        patterns:
          - "Microsoft.AspNetCore*"
      ai:
        patterns:
          - "Microsoft.Extensions.AI*"

  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "weekly"
    assignees:
      - "sys27"
    cooldown:
      default-days: 7
    groups:
      react-router:
        patterns:
          - "*react-router*"
      react-query:
        patterns:
          - "@tanstack/*-query"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "sys27"
    cooldown:
      default-days: 7
