// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(KbDbContext))]
    [Migration("20260421130429_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Backend.Chats.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSummaryUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_Chats");

                    b.HasIndex(new[] { "ProjectId" }, "IX_Chats_ProjectId");

                    b.ToTable("Chats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            Title = "Chat 1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Chat 2"
                        });
                });

            modelBuilder.Entity("Backend.Chats.ChatDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ChatDecisions");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("IX_ChatDecisions_ChatId");

                    b.ToTable("ChatDecisions", (string)null);
                });

            modelBuilder.Entity("Backend.Chats.ChatFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fact")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ChatFacts");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("IX_ChatFacts_ChatId");

                    b.ToTable("ChatFacts", (string)null);
                });

            modelBuilder.Entity("Backend.Chats.ChatTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ChatTopics");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("IX_ChatTopics_ChatId");

                    b.ToTable("ChatTopics", (string)null);
                });

            modelBuilder.Entity("Backend.Chats.ChatUserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Preference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ChatUserPreferences");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("IX_ChatUserPreferences_ChatId");

                    b.ToTable("ChatUserPreferences", (string)null);
                });

            modelBuilder.Entity("Backend.Ingestion.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_Documents");

                    b.HasIndex(new[] { "ProjectId" }, "IX_Documents_ProjectId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Backend.Ingestion.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Start")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_DocumentChunks");

                    b.HasIndex(new[] { "DocumentId" }, "IX_DocumentChunks_DocumentId");

                    b.ToTable("DocumentChunks", (string)null);
                });

            modelBuilder.Entity("Backend.Messages.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_Messages");

                    b.HasIndex(new[] { "ChatId" }, "IX_Messages_ChatId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Backend.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_Projects");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "test"
                        });
                });

            modelBuilder.Entity("Backend.Chats.Chat", b =>
                {
                    b.HasOne("Backend.Projects.Project", "Project")
                        .WithMany("Chats")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Chats_Projects_ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Backend.Chats.ChatDecision", b =>
                {
                    b.HasOne("Backend.Chats.Chat", "Chat")
                        .WithMany("Decisions")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChatDecisions_Chats_ChatId");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Backend.Chats.ChatFact", b =>
                {
                    b.HasOne("Backend.Chats.Chat", "Chat")
                        .WithMany("Facts")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChatFacts_Chats_ChatId");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Backend.Chats.ChatTopic", b =>
                {
                    b.HasOne("Backend.Chats.Chat", "Chat")
                        .WithMany("Topics")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChatTopics_Chats_ChatId");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Backend.Chats.ChatUserPreference", b =>
                {
                    b.HasOne("Backend.Chats.Chat", "Chat")
                        .WithMany("UserPreferences")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChatUserPreferences_Chats_ChatId");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Backend.Ingestion.Document", b =>
                {
                    b.HasOne("Backend.Projects.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Documents_Projects_ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Backend.Ingestion.DocumentChunk", b =>
                {
                    b.HasOne("Backend.Ingestion.Document", "Document")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentChunks_Documents_DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Backend.Messages.Message", b =>
                {
                    b.HasOne("Backend.Chats.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Backend.Chats.Chat", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Facts");

                    b.Navigation("Messages");

                    b.Navigation("Topics");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Backend.Ingestion.Document", b =>
                {
                    b.Navigation("DocumentChunks");
                });

            modelBuilder.Entity("Backend.Projects.Project", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
